Typescript
quiltt/style pull request #2
Opened 2022-01-18 05:05 UTC by zubairaziz

This turns our current `ESLint` + `Prettier` settings into an npm package, making installation and setup for styling/formatting much simpler.

Our new `.eslintrc` file would look like this with this package installed:

```json
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "extends": ["quiltt/typescript"],
}
```

2022-01-19 17:12 UTC, sirwolfgang requested changes

2022-01-19 17:12 UTC, sirwolfgang commented on typescript/.nvmrc
> +v16
For this repo, I want to focus on values and not rules. In this case, I think the value might be:

- Communicate the node version using a `.nvmrc` within a project

This can go in the readme, but I would avoid putting this file in here, since we are not saying:

- All typescript projects should use node version `v16`

Is this needed to support the other scripts or something?

2022-01-24 19:02 UTC, sirwolfgang approved these changes
Pending the changes discussed at standup

2022-01-24 20:18 UTC, rubendinho approved these changes

2022-01-26 00:09 UTC, merged